#!/usr/bin/env python3
"""Module that defines function async_comprehension
"""
import asyncio
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """Creates a list of random numbers generated by asynchronous generator"""

    lst: List[float] = [i async for i in async_generator()]

    return lst
